
psql $DATABASE_URL -c "DROP TABLE IF EXISTS notes"
psql $DATABASE_URL -c "DROP TABLE IF EXISTS topics"
psql $DATABASE_URL -c "DROP TABLE IF EXISTS notebooks"
psql $DATABASE_URL -c "DROP TABLE IF EXISTS sections"
psql $DATABASE_URL -c "DROP TABLE IF EXISTS courses"
psql $DATABASE_URL -c "DROP TABLE IF EXISTS schools"
psql $DATABASE_URL -c "DROP TABLE IF EXISTS users"
